// Mock data based on energy management dashboard

export const dashboardStats = {
  totalSites: 50,
  alerts: 26,
  noComms: 16,
  mwInstalled: 45.7,
  liveOutputMw: 14.2,
  avgSocPercent: 67,
  revenueMonth: 1284500,
  currency: "ILS",
};

// Enums / constants
export const SITE_TYPES = ["PV", "BESS", "PV+BESS", "BTM", "TOU"];
export const SITE_STATUSES = [
  "Active",
  "Maintenance",
  "Planned",
  "Decommissioned",
];
export const REGIONS = ["Tel Aviv", "North", "South", "Center", "Jerusalem"];
export const OWNERS = ["AGEERA", "3rd Party"];
export const COMM_STATUSES = ["OK", "No Comm", "Intermittent"];

/**
 * @typedef {Object} Site
 * @property {string}  id           - Unique system ID
 * @property {string}  displayName  - Human-readable site name
 * @property {string}  type         - One of SITE_TYPES
 * @property {string}  status       - One of SITE_STATUSES
 * @property {string}  customer     - Customer / company name
 * @property {string}  region       - One of REGIONS
 * @property {number}  capacityKwh  - Energy capacity in kWh
 * @property {number}  capacityKw   - Power capacity in kW
 * @property {number}  socPercent   - State of charge 0-100
 * @property {string}  commStatus   - One of COMM_STATUSES
 * @property {string}  owner        - One of OWNERS
 * @property {boolean} hasAlert     - Whether the site has an active alert
 */

export const sites = [
  {
    id: "IL_PVBESS_TelAviv_AGR-001",
    displayName: "Dorad Energy - Industrial Park",
    type: "PV+BESS",
    status: "Active",
    customer: "Dorad Energy",
    region: "Tel Aviv",
    capacityKwh: 1200,
    capacityKw: 600,
    socPercent: 65,
    commStatus: "OK",
    owner: "AGEERA",
    hasAlert: true,
  },
  {
    id: "IL_PV_North_AGR-002",
    displayName: "Nofar Energy - Kibbutz Yizreel",
    type: "PV",
    status: "Maintenance",
    customer: "Nofar Energy",
    region: "North",
    capacityKwh: 800,
    capacityKw: 400,
    socPercent: 42,
    commStatus: "OK",
    owner: "3rd Party",
    hasAlert: true,
  },
  {
    id: "IL_BESS_South_AGR-003",
    displayName: "Harel Insurance - Logistics Hub",
    type: "BESS",
    status: "Active",
    customer: "Harel Insurance",
    region: "South",
    capacityKwh: 2000,
    capacityKw: 1000,
    socPercent: 15,
    commStatus: "No Comm",
    owner: "AGEERA",
    hasAlert: true,
  },
  {
    id: "IL_BTM_Center_AGR-004",
    displayName: "Azrieli Group - Sarona Tower",
    type: "BTM",
    status: "Planned",
    customer: "Azrieli Group",
    region: "Center",
    capacityKwh: 500,
    capacityKw: 250,
    socPercent: 0,
    commStatus: "OK",
    owner: "3rd Party",
    hasAlert: false,
  },
  {
    id: "IL_TOU_Jerusalem_AGR-005",
    displayName: "Government Complex - Ministry Campus",
    type: "TOU",
    status: "Active",
    customer: "Israel Govt",
    region: "Jerusalem",
    capacityKwh: 1500,
    capacityKw: 750,
    socPercent: 88,
    commStatus: "OK",
    owner: "3rd Party",
    hasAlert: false,
  },
  {
    id: "IL_PVBESS_North_AGR-006",
    displayName: "Paz Oil - Haifa Port",
    type: "PV+BESS",
    status: "Active",
    customer: "Paz Oil",
    region: "North",
    capacityKwh: 2500,
    capacityKw: 1250,
    socPercent: 55,
    commStatus: "Intermittent",
    owner: "3rd Party",
    hasAlert: true,
  },
  {
    id: "IL_BESS_TelAviv_AGR-007",
    displayName: "Electra - Office Building",
    type: "BESS",
    status: "Decommissioned",
    customer: "Electra",
    region: "Tel Aviv",
    capacityKwh: 400,
    capacityKw: 200,
    socPercent: 5,
    commStatus: "No Comm",
    owner: "3rd Party",
    hasAlert: false,
  },
  {
    id: "IL_PV_South_AGR-008",
    displayName: "Enlight - Solar Field South",
    type: "PV",
    status: "Active",
    customer: "Enlight",
    region: "South",
    capacityKwh: 5000,
    capacityKw: 2500,
    socPercent: 95,
    commStatus: "OK",
    owner: "3rd Party",
    hasAlert: false,
  },
  {
    id: "IL_BESS_Center_AGR-009",
    displayName: "Shikun & Binui - Rishon Complex",
    type: "BESS",
    status: "Active",
    customer: "Shikun & Binui",
    region: "Center",
    capacityKwh: 1800,
    capacityKw: 900,
    socPercent: 72,
    commStatus: "OK",
    owner: "AGEERA",
    hasAlert: false,
  },
  {
    id: "IL_PVBESS_Jerusalem_AGR-010",
    displayName: "Jerusalem Economy - Business Park",
    type: "PV+BESS",
    status: "Active",
    customer: "Jerusalem Economy",
    region: "Jerusalem",
    capacityKwh: 3000,
    capacityKw: 1500,
    socPercent: 61,
    commStatus: "OK",
    owner: "AGEERA",
    hasAlert: true,
  },
  {
    id: "IL_PV_North_AGR-011",
    displayName: "Solbar - Kibbutz Naan Fields",
    type: "PV",
    status: "Active",
    customer: "Solbar",
    region: "North",
    capacityKwh: 6000,
    capacityKw: 3000,
    socPercent: 80,
    commStatus: "OK",
    owner: "3rd Party",
    hasAlert: false,
  },
  {
    id: "IL_BTM_TelAviv_AGR-012",
    displayName: "WeWork - Rothschild Tower",
    type: "BTM",
    status: "Active",
    customer: "WeWork",
    region: "Tel Aviv",
    capacityKwh: 300,
    capacityKw: 150,
    socPercent: 90,
    commStatus: "OK",
    owner: "3rd Party",
    hasAlert: false,
  },
  {
    id: "IL_TOU_South_AGR-013",
    displayName: "ICL - Dead Sea Plant",
    type: "TOU",
    status: "Maintenance",
    customer: "ICL Group",
    region: "South",
    capacityKwh: 4000,
    capacityKw: 2000,
    socPercent: 33,
    commStatus: "Intermittent",
    owner: "AGEERA",
    hasAlert: true,
  },
  {
    id: "IL_BESS_North_AGR-014",
    displayName: "Tnuva - Northern Dairy Plant",
    type: "BESS",
    status: "Active",
    customer: "Tnuva",
    region: "North",
    capacityKwh: 1200,
    capacityKw: 600,
    socPercent: 58,
    commStatus: "No Comm",
    owner: "3rd Party",
    hasAlert: true,
  },
  {
    id: "IL_PV_Center_AGR-015",
    displayName: "Gav-Yam - Herzliya Pituach",
    type: "PV",
    status: "Active",
    customer: "Gav-Yam",
    region: "Center",
    capacityKwh: 2200,
    capacityKw: 1100,
    socPercent: 77,
    commStatus: "OK",
    owner: "AGEERA",
    hasAlert: false,
  },
  {
    id: "IL_PVBESS_South_AGR-016",
    displayName: "Ormat - Geothermal & Solar",
    type: "PV+BESS",
    status: "Active",
    customer: "Ormat Technologies",
    region: "South",
    capacityKwh: 7500,
    capacityKw: 3750,
    socPercent: 84,
    commStatus: "OK",
    owner: "AGEERA",
    hasAlert: false,
  },
  {
    id: "IL_BTM_Jerusalem_AGR-017",
    displayName: "Hebrew University - Givat Ram",
    type: "BTM",
    status: "Active",
    customer: "Hebrew University",
    region: "Jerusalem",
    capacityKwh: 600,
    capacityKw: 300,
    socPercent: 69,
    commStatus: "OK",
    owner: "3rd Party",
    hasAlert: false,
  },
  {
    id: "IL_BESS_TelAviv_AGR-018",
    displayName: "Bank Leumi - Data Center",
    type: "BESS",
    status: "Active",
    customer: "Bank Leumi",
    region: "Tel Aviv",
    capacityKwh: 900,
    capacityKw: 450,
    socPercent: 91,
    commStatus: "OK",
    owner: "AGEERA",
    hasAlert: true,
  },
  {
    id: "IL_PV_South_AGR-019",
    displayName: "Ketura Sun - Arava Valley",
    type: "PV",
    status: "Active",
    customer: "Ketura Sun",
    region: "South",
    capacityKwh: 10000,
    capacityKw: 5000,
    socPercent: 99,
    commStatus: "OK",
    owner: "3rd Party",
    hasAlert: false,
  },
  {
    id: "IL_TOU_Center_AGR-020",
    displayName: "Intel - Kiryat Gat Fab",
    type: "TOU",
    status: "Planned",
    customer: "Intel Israel",
    region: "Center",
    capacityKwh: 3500,
    capacityKw: 1750,
    socPercent: 0,
    commStatus: "No Comm",
    owner: "3rd Party",
    hasAlert: false,
  },
];
